### ISSUE TITLE
HTML in Markdown

### ISSUE THREAD

**Issue by marian2js** [wooorm/strip-markdown#19] opened 2020-09-10 23:16 UTC
### Subject of the issue

Strings starting with `<p>...</p>` cause everything else to be dropped.

```js
remark()
  .use(strip)
  .process('<p>foo</p> bar', function(err, file) {
    if (err) throw err
    console.log(String(file))
  })
```

Actual: ""
Expected: "foo bar"

With some text before the tag, it works as expected:

```js
remark()
  .use(strip)
  .process('foo <p>bar</p>', function(err, file) {
    if (err) throw err
    console.log(String(file))
  })
```

Actual: "foo bar"

### Your environment

*   **OS**: macOS 10.15.5
*   **Packages**: strip-markdown "3.1.2"
*   **Env**: node 14

### Steps to reproduce

The issue can also be reproduced on the [demo](http://remarkjs.github.io/strip-markdown/), just enter:

```
<p>foo</p>
bar
```

### Expected behavior

`<p>` tag should be stripped and the inner text should be returned. This behavior works with other tags like `<span>`.

### Actual behavior

`<p>foo</p> bar` returns an empty string, but `foo <p>bar</p>` returns "foo bar".

**Comment by wooorm** [comment] 2020-10-03 11:10
hey, sorry for the wait, was busy with other stuff!

This is a duplicate of https://github.com/remarkjs/strip-markdown/issues/14, the answer is still the same!

**Closed as completed by wooorm** 2020-10-03 11:10 UTC
Labels: 👯 no/duplicate

**Comment by marian2js** [comment] 2020-10-03 16:10
Hi @wooorm thanks for the reply. I wasn't expecting this to be a hard fix, since it works for tags like `span` but not for `p`.

As a workaround I prefixed the text with a character and stripe it after words, it's not very elegant, but it seems to work for all cases. Maybe a similar workaround can be introduced in this library in order to prevent unexpected behaviours.

**Comment by wooorm** [comment] 2020-10-03 16:17
The proper way to deal with HTML is through remark-rehype, rehype-raw, and then getting the text.
I understand this workaround works well for you, but I’d rather not introduce something fragile into the code here!

**Comment by marian2js** [comment] 2020-10-03 20:07
Hi @wooorm, it's fine if the workaround is not added, but I think this should be documented. The readme says this library removes HTML, but now you say the proper way is to use extra plugins for it. I was replacing a different implementation with this library and I was lucky that a test was covering this case, otherwise I might not have detected it until production.

Anyway, thanks for maintaining this project, it was really useful for me.

**Comment by wooorm** [comment] 2020-10-04 06:45
I think what’s confusing here is:

```html
<p>foo</p> *bar*
```

^-- this whole thing is HTML to markdown. The emphasis doesn’t work. The docs refer to that aspect of HTML in markdown. But from what I gather, you’re reading `html` as just the XML-like parts of HTML, but not the text in HTML.

**Comment by wooorm** [comment] 2020-10-04 06:47
Added a link to this issue next to where the readme mentions HTML!
