### ISSUE TITLE
Removing alt text for images

### ISSUE THREAD

**Issue by KulkiratSingh** [wooorm/strip-markdown#23] opened 2021-04-29 23:03 UTC
### Removing alt text for images

Is there a way we can disable alt text for images ?

**Comment by ChristianMurphy** [comment] 2021-04-30 00:05
This plugin is designed to remove formatting, not remove alt text specifically.
This is also a duplicate of the question https://github.com/remarkjs/remark/discussions/702

**Closed as completed by ChristianMurphy** 2021-04-30 00:05 UTC
Labels: 👯 no/duplicate, 🙋 no/question
